Repository losete/springboot-crud-demo, pull requests merged in 2019-11, with the labels that each got.

#1 fix/solve_dependency_problems
  pom.xml
  src/main/resources/application.properties
  src/test/java/com/ensat/WebAppApplicationTests.java
Labels: bug

#2 enhancement/pom_plugin_update
  pom.xml
Labels: enhancement

#3 enhancement/dockerize db
  .gitignore
  dist/docker/docker-compose.yml
Labels: enhancement

#6 enhancement/add_checkstyle
  checkstyle.xml
  pom.xml
  src/main/java/com/ensat/SpringBootWebApplication.java
  src/main/java/com/ensat/controllers/IndexController.java
  src/main/java/com/ensat/controllers/ProductController.java
  src/main/java/com/ensat/entities/Product.java
  src/main/java/com/ensat/services/ProductService.java
  src/main/java/com/ensat/services/ProductServiceImpl.java
Labels: enhancement

#7 enhancement/add_spotbugs
  pom.xml
  src/main/config/spotbugs-exclude-filter.xml
  src/main/java/com/ensat/controllers/IndexController.java
Labels: enhancement

#5 Fix maven version Issue
  pom.xml
Labels: configuration, enhancement

#8 enhancement/add_sortpom
  pom.xml
  src/main/config/pom_stylesheet.xml
Labels: enhancement

#9 enhancement/benchmarking
  benchmarks/pom.xml
  benchmarks/src/main/java/com/ensat/benchmarks/BenchmarkTests.java
  pom.xml
  src/main/config/spotbugs-exclude-filter.xml
  web/pom.xml
  web/src/main/java/com/ensat/SpringBootWebApplication.java
  web/src/main/java/com/ensat/controllers/IndexController.java
  web/src/main/java/com/ensat/controllers/ProductController.java
  web/src/main/java/com/ensat/entities/Product.java
  web/src/main/java/com/ensat/repositories/ProductRepository.java
  web/src/main/java/com/ensat/services/ProductService.java
  web/src/main/java/com/ensat/services/ProductServiceImpl.java
  web/src/main/resources/application.properties
  web/src/main/resources/static/css/bootstrap.min.css
  web/src/main/resources/static/css/style.css
  web/src/main/resources/static/images/boot.png
  web/src/main/resources/templates/fragments/header.html
  web/src/main/resources/templates/fragments/headerinc.html
  web/src/main/resources/templates/index.html
  web/src/main/resources/templates/productform.html
  web/src/main/resources/templates/products.html
  web/src/main/resources/templates/productshow.html
  web/src/test/java/com/ensat/WebAppApplicationTests.java
Labels: enhancement

#4 enhancement/pick_password_from_parameter
  web/src/main/resources/application.properties
Labels: enhancement

#10 enhancement/add_jacoco
  pom.xml
Labels: enhancement

#11 fix/properties
  web/src/main/resources/application.properties
Labels: bug
